### ISSUE TITLE
データベースの環境構築

### ISSUE THREAD

**Issue by githubeWYrd4nG** [ChaSaji/PickNic#11]
ReactNativeで動くデータベースの作成及びフロントエンドとの連携

**Comment by githubeWYrd4nG** [comment]
SQLite3を
https://www.sqlite.org/download.html
からダウンロード

**Comment by githubeWYrd4nG** [comment]
を参考に環境構築(installで行ける可能性はある)
https://naoto-kagaya.com/articles/2023-02-21-react-native-sqlite-storage-chatgpt

**Comment by endo1322** [comment]
expoでのsqliteのドキュメント
https://docs.expo.dev/versions/latest/sdk/sqlite/

**Comment by githubeWYrd4nG** [comment]
npx expo install --fix
を実行
