### ISSUE TITLE
俺の開発環境の問題

### ISSUE THREAD

**Issue by Ilekaede** [ChaSaji/PickNic#15]
# featureブランチが切れないので全部手打ちでファイル作成，コードのコピーをしています．つらい

## featureブランチを切っても自分の環境に反映されてない

# Help Me!

**Comment by endo1322** [comment]
今日来る？

**Comment by Ilekaede** [comment]
解決した
・git pullで常に最新状態を引っ張ってくる
・最新状態であるかgitGraphとにらめっこ
・pull requestはmerge先をdevelopにする
・git branch -rでブランチすべて確認できる
