### ISSUE TITLE
データベースから取ってきたデータを列挙する(レシピ，称号など)

### ISSUE THREAD

**Issue by Ilekaede** [ChaSaji/PickNic#16]
データベースから取ってきたデータを並べる．
スクロールで下までスライドできるようにする．
UI周り

**Comment by endo1322** [comment]
react-navigationのインストール
https://reactnative.dev/docs/navigation
https://reactnavigation.org/docs/bottom-tab-navigator/
bottom tabs navigatorの作成
https://reactnavigation.org/docs/bottom-tab-navigator/を参考
