### ISSUE TITLE
schema.eventDetailにIDの追加

### ISSUE THREAD

**Issue by endo1322** [ChaSaji/PickNic#197]
https://github.com/ChaSaji/PickNic/blob/f36f3ee56286add405da9a65abac811377d5c655/api/api/schemes/event.py#L24-L25

見落としましが、GET `events/{event_id}`の返り値でもあるEventDetailの要素の`id`は消さないでください。
多分気持ちとしては、idを入力で受け取ってidを返す必要はないということだと思いますが、responseにidがないと以降の処理で、idだけ入力に与えたものを使うなどとコードの複雑性が増します。
例えば以下のような処理ができないです。
```javascript
export const getEventDetail = async (eventId) => {
  const data = await fetchAPI({ endpoint: `events/${eventId}` });
  const eventData = {
    id: data.id,
    name: data.event_name,
    organizer: data.organizer,
    startDate: formatDate(data.start_date),
    endDate: formatDate(data.end_date),
    latitude: data.latitude,
    longitude: data.longitude,
    orverview: data.orverview,
  };

  return eventData;
};
```

**Comment by Ilekaede** [comment]
追加しておきました
