### ISSUE TITLE
migrate時の初期値生成

### ISSUE THREAD

**Issue by Ilekaede** [ChaSaji/PickNic#209]
sqlalchemyseedを利用して，migrate時にDBに幾つかの初期データが自動でクリエイトされるようにします．

**Comment by endo1322** [comment]
`test.db`の追跡を外すことだけしておきました。

**Comment by Ilekaede** [comment]
seed値を入れる際に，seed_data.json内の日付を表す文字列をdatetime型に変換する処理が必要なのですが，これをやる必要があるのか少しだけ疑問に思ってしまった．
日付だけ後入れで型変更したものを入れられないか考えている．

**Comment by endo1322** [comment]
あくまで 、DBに入れるデータだからフォーマットあってれば入ると思うんだよなぁ。。多分。。
```
"start_date": "2023-01-01T00:00:00",
```

**Comment by Ilekaede** [comment]
とりあえずdatetime型に変換して入れる処理作って対応しました．そのままは無理ぽでした

**Comment by Ilekaede** [comment]
relationだけできてなさそうから後で確認したいです．
それ以外はちゃんと入ってる．

**Comment by Ilekaede** [comment]
用事で帰るからとりあえずpushだけしておきました．
