### ISSUE TITLE
スクリーンをスタックスクリーンに統一する

### ISSUE THREAD

**Issue by Ilekaede** [ChaSaji/PickNic#32]
#29 でホームとカメラのみがスタックスクリーンになっていて他はタブスクリーンとなっている．
キモいので統一する．

メリット -> 画面最上部がスッキリする．

**Comment by endo1322** [comment]
直感的で分かりやすいから参考にしたいです。
この[記事](https://qiita.com/nakapon9517/items/6b99adc29e4597ed47e1)でもこんな感じの構成になってました。

以下ChatGPTさんからのおすすめです。

####################################################
React NativeでMaterial Bottom TabsとStack Navigatorを組み合わせて使用する場合、直感的で管理しやすいディレクトリ構成とファイル名の命名規則を採用することが重要です。ここでは、一般的な構成として推奨される方法を紹介します。

### ディレクトリ構成の例
以下のディレクトリ構成は、アプリケーションの規模や特定の要件に応じて調整できますが、スタート地点として役立ちます。

```
/src
  /navigation
    AppNavigator.js (または .tsx)
    /stacks
      HomeStack.js (または .tsx)
      SettingsStack.js (または .tsx)
      ... (その他のスタックナビゲーター)
  /screens
    /home
      HomeScreen.js (または .tsx)
      DetailScreen.js (または .tsx)
      ... (その他のホーム関連のスクリーン)
    /settings
      SettingsScreen.js (または .tsx)
      AccountScreen.js (または .tsx)
      ... (その他の設定関連のスクリーン)
    ... (その他のカテゴリ)
  /components
    ... (共有コンポーネント)
  /assets
    ... (画像やフォントなどのアセット)
```
### ファイル名とコンポーネントの命名規則
- スタックナビゲーター: 各スタックナビゲーターのファイル名は、そのナビゲーターが含む主要なスクリーンまたは機能に基づいて名付けます。例えば、HomeStack.jsはホーム画面とその関連画面を管理します。
- スクリーン: スクリーンコンポーネントのファイル名は、そのスクリーンが何を表しているかに基づいて明確に名付けます。例えば、HomeScreen.jsやSettingsScreen.jsのようにします。
- 共有コンポーネント: /componentsディレクトリには、アプリケーション全体で再利用可能なUIコンポーネントを配置します。それぞれのコンポーネントはその機能または用途に応じた名前をつけます。例えば、Button.jsやAvatar.jsのようにします。
### おすすめの実装手順
- ナビゲーション構成の設計: アプリの全体的なナビゲーションフローを設計します。どのスクリーンがボトムタブに含まれ、どのスクリーンがスタックナビゲーター内でナビゲーションされるかを決定します。
- スタックナビゲーターの作成: 各タブに対応するスタックナビゲーターを/navigation/stacks内に作成します。これにより、タブ内のスクリーン間でのナビゲーションが可能になります。
- ボトムタブナビゲーターの設定: AppNavigator.js内でMaterial Bottom Tabsを設定し、先に作成したスタックナビゲーターをタブとして追加します。

この構成と命名規則を使用することで、React Nativeアプリのナビゲーションを効果的に管理し、開発プロセスをスムーズに進めることができます。
####################################################
