### ISSUE TITLE
カレーを作るためのアイテムをExelシートに記入

### ISSUE THREAD

**Issue by karin26801684** [ChaSaji/PickNic#51]

**Comment by endo1322** [comment]
### やること
エクセルの表にDBに登録するためのデータを記入

### 登録するデータ内容
以下注意ごと
色情報はネイティブでは管理しないことにします。
カラムに対する値を全部書いている訳じゃないです。
最低限登録して欲しいこととや、注意が入りそうなところをニュアンスで書いているので参考程度で見てください。
よくわかんなかったら聞いてください。

- meal
  - id:1
    - name: カレー（name属性ないかも、一旦そのまま進めて）
    - badgeId: 1
    - meal_status: mealIdと同じidで
    - meal_image_path: 実際にアプリで使う画像を持ってきてassets/に保存、そこまでのパス
- meal_status（多分mealひとつに対してひとつ割り当てられるようにするテーブル）
  - id: 1
    - locked: 1or0(ロックされてれば1、解除は0？)
    - cooked: 1or0(料理されてれば1、されてなければ0？)
- material
  - にんじん、じゃがいも、豚肉、玉ねぎそれぞれ
- recipe
  - recipeId: 一旦mealと同じでいいです（カレー（１））
- recipe_detail x 4
  - recepiId: カレー（1）
  - materialId : materialそれぞれ
  - needNum: 一旦任せます。
- badge
  - id: 1
  - name: 懐かしの給食
  - flag: 0
  - badge_image_path: 実際の画像パス
