### ISSUE TITLE
excelとDBのカラム名があっていない

### ISSUE THREAD

**Issue by endo1322** [ChaSaji/PickNic#53]
material テーブルがmealの内容になっていたり

**Comment by karin26801684** [comment]
badthIDが何か分からない
photoの名前がいらない（修正がめんどかったらしなくても良い）
photoのIDがない
materialに名前を追加してほしい（UIで表示するときに使う）
materialに色情報がほしい（OpenCVで検出した色のmaterialを持って来たいから）

**Comment by githubeWYrd4nG** [comment]
badthIDはBadgeのIDです実コードとmiroの記述わかりやすい名前に変えておきます
他の記述についても見ておきます

**Comment by githubeWYrd4nG** [comment]
あとPhotoのIDが無いというのはExcelファイルでID情報を明記したいということですか？
そうなると上から順に読まれるので、行数がそのままIDになります

**Comment by githubeWYrd4nG** [comment]
colorについてはおそらくいらないだろうとのことで追加を見送りました。
もし必要な場合はデータ型RGBなのかそれともIDと名前の組なのかを教えてください。
