### ISSUE TITLE
撮影した写真をマテリアルに変換する間のロード画面の作成

### ISSUE THREAD

**Issue by endo1322** [ChaSaji/PickNic#77]
### やること
- ロード中のアニメーションスクリーンの作成（CookingAnimationScreen.js参考）
- 変換ボタンを押して上記スクリーンに遷移するよう変更
- 変換先のアイテムの情報が入ってきたら、GetMaterialScreen.jsに遷移
- 変換先のアイテム取得中にエラー（通信エラーなど）拾った場合、PictureScreen.jsに戻るなどの対応

**Comment by Ilekaede** [comment]
変換ボタン連打すると複数回GET画面が出てきたかもしれない(かもしれないなので確認必要かも)
